version: 1.0.{build}
image: Visual Studio 2017

environment:
  access_token:
    secure: 3Pc4S+ZcBNEiqJDWthe96uDsSJSeW2Rsb1UckEq8Tp/niew5yx8bA3uUYcHaCQ4G

configuration: Release
platform: Any CPU

before_build:
  - nuget restore

build:
  project: Foo.sln
  verbosity: minimal

test_script:
- cmd: >-
    dotnet test --logger:Appveyor Foo.Test\Foo.Test.csproj -c Release 

deploy_script:
- cmd: >-
    git subtree push --prefix=Foo.Lib git@github.com:gregmeess/Foo.Lib.git release