version: 1.0.{build}
image: Visual Studio 2017

build_script:
- cmd: >-
    dotnet restore Foo.sln
    
    dotnet build Foo.sln -c Release

test_script:
- cmd: >-
    vstest.console /logger:Appveyor Foo.Test/Foo.Test.csproj