version: 1.0.{build}
image: Visual Studio 2017

configuration: Release
platform: Any CPU

before_build:
  - nuget restore

build:
  project: Foo.sln
  verbosity: minimal

test: 
  assemblies:
     - C:\projects\foo\Foo.Test\bin\Release\netcoreapp2.1\Foo.Test.dll

