version: 1.0.{build}
image: Visual Studio 2017

build_script:
- cmd: >-
    dotnet restore Foo.sln
    
    dotnet build Foo.sln -c Release

test_script:
- cmd: >-
    dotnet test Foo.Test\Foo.Test.sln -c Release
