version: '1.0.{build}'
image: Visual Studio 2017

#patch version in csproj file 
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
- cmd: >-
    dotnet restore geometry3Sharp_netstandard.csproj
    dotnet build geometry3Sharp_netstandard.csproj -c Release
    dotnet pack geometry3Sharp_netstandard.csproj -c Release
test: on